# Generated by Django 2.1.1 on 2018-09-30 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SklearnModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField()),
                ('model_type', models.CharField(choices=[('classification', 'classification'), ('regression', 'regression')], default='classification', max_length=100)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
